### ISSUE TITLE
Link to latest Rakudo Star

### ISSUE THREAD

**Issue by fecundf** [hankache/rakuguide#218]
Thanks for the excellent raku.guide! I am preparing an Intro to Raku talk and will include a link.

Near the start, about installing Rakudo Star on Linux, is a little out of date– linking to .01 when there is now .10 available.

I think the right fix is two changes:

1. work with rakudo.org and have them institute a “.latest” link on https://rakudo.org/downloads/star so that anyone writing docs can have instructions that reference downloads/star/rakudo-star-2020.01.latest.gz and it will always be the latest.
2. Link to the latest

I wanted to cc the owners of rakudo.org but didn’t find an email for that site. Hope you have a contact there! I can jump on raku IRC if it will help.

If changing rakudo.org download links is too out-of-scope, at least updating to 2020.10 would be good.

**Comment by hankache** [comment]
Hello @fecundf,

Thank you for your feedback! I am glad that you found raku.guide useful.

I updated the instructions temporarily to 2020.10 so that readers get the latest star version. Nonetheless there is a latest link that could be used https://rakudo.org/latest/star/src

Feel free to open more issues if needed and/or submit pull requests if you feel like doing the change yourself.

For the time being I am keeping this issue open until we use the latest link in the guide.

Thanks
